api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import PostModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'post', PostModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

app_ToDo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from posts.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', obtain_auth_token),
]


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts.views import (PostCreateView, PostsListView, PostUpdateView,
                         not_actuality, post_delete)

app_name = 'posts'

urlpatterns = [
    path('', PostsListView.as_view(), name='posts_list'),
    path('post_create/', PostCreateView.as_view(), name='post_create'),
    path('post_update/<int:pk>', PostUpdateView.as_view(), name='post_update'),
    path('post_not_actuality/', not_actuality, name='post_not_actuality'),
    path('post_delete/<int:post_id>', post_delete, name='post_delete'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegistrationView)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/<int:pk>', UserProfileView.as_view(), name='profile'),
    path('email_verification/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

posts/models.py
from django.db import models

from users.models import User


class Post(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)
    actuality = models.BooleanField(default=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-actuality', '-created_timestamp')

    def __str__(self):
        return self.name

    @classmethod
    def post_not_actuality(self, user):
        posts = Post.objects.filter(user=user)
        post = posts.first()
        post.actuality = False
        post.save()
        return post

posts/forms.py
from django import forms

from posts.models import Post


class PostCreateForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите название заметки',
    }))
    description = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите описание заметки',
    }))
    actuality = forms.CharField(widget=forms.CheckboxInput(attrs={
        'class': 'form-check-input',
    }))

    class Meta:
        model = Post
        fields = ('name', 'description', 'actuality')

posts/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from common.views import TitleMixin
from posts.forms import PostCreateForm
from posts.models import Post


class IndexView(TitleMixin, TemplateView):
    template_name = 'posts/index.html'
    title = 'ToDo'


class PostsListView(TitleMixin, ListView):
    model = Post
    template_name = 'posts/posts.html'
    title = 'ToDo - Напоминания'
    paginate_by = 6

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)


class PostCreateView(TitleMixin, CreateView):
    model = Post
    template_name = 'posts/post_create.html'
    title = 'ToDo - Создание заметки'
    form_class = PostCreateForm
    success_url = reverse_lazy('posts:posts_list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class PostUpdateView(TitleMixin, UpdateView):
    model = Post
    template_name = 'posts/post_create.html'
    title = 'ToDo - Изменение заметки'
    form_class = PostCreateForm
    success_url = reverse_lazy('posts:posts_list')

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)


def not_actuality(request):
    Post.post_not_actuality(user=request.user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def post_delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

posts/templates/posts/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ title }}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="icon" href="">
</head>
<body>
  <header>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container">
        <a href="{% url 'index' %}" class="navbar-brand d-flex align-items-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bootstrap" viewBox="0 0 16 16">
            <path d="M5.062 12h3.475c1.804 0 2.888-.908 2.888-2.396 0-1.102-.761-1.916-1.904-2.034v-.1c.832-.14 1.482-.93 1.482-1.816 0-1.3-.955-2.11-2.542-2.11H5.062V12zm1.313-4.875V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23H6.375zm0 3.762V8.162h1.822c1.236 0 1.887.463 1.887 1.348 0 .896-.627 1.377-1.811 1.377H6.375z"/>
            <path d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4zm4-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3H4z"/>
          </svg>
          <strong>ToDo</strong>
        </a>
        <div class="col-sm-4 offset-md-1 py-4">-->
          <ul class="list-unstyled">
            {% if user.is_authenticated %}
              <li><a href="{% url 'posts:posts_list' %}" class="text-white">Главная</a></li>
              <li><a href="{% url 'posts:post_create' %}" class="text-white">Добавить заметку</a></li>
              <li><a href="{% url 'users:profile' user.id %}" class="text-white">Профиль</a></li>
              {% if user.is_superuser or user.is_staff %}
                <li><a href="{% url 'admin:index' %}" class="text-white">Админ-панель</a></li>
              {% endif %}
              <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
            {% else %}
              <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
              <li><a href="{% url 'users:registration' %}" class="text-white">Зарегистрироваться</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </header>

  {% block content %}{% endblock %}

  <footer class="text-muted py-5">
    <div class="container">
      <p class="float-end mb-1">
        <a href="#">Back to top</a>
      </p>
      <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
      <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
  </footer>

      <script src="/docs/5.3/dist/js/bootstrap.bundle.min.js"
              integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
              crossorigin="anonymous"></script>
</body>
</html>

posts/templates/posts/index.html
{% extends 'posts/base.html' %}

{% block content %}
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">ToDo</h1>
        <p class="lead text-muted">Заметки на каждый день</p>
        <p>
          {% if not user.is_authenticated %}
            <a href="{% url 'users:login' %}" class="btn btn-primary my-2">Войти</a>
            <a href="{% url 'users:registration' %}" class="btn btn-secondary my-2">Зарегистрироваться</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>
{% endblock %}

posts/templates/posts/post_create.html
{% extends 'posts/base.html' %}

{% block content %}
  <div class="container">
    {% if not object %}
      <form action="{% url 'posts:post_create' %}" method="post">
    {% else %}
      <form action="{% url 'posts:post_update' object.id %}" method="post">
    {% endif %}
        {% csrf_token %}
        <div class="mb-3">
          <label for="{{ form.name.id_for_label }}" class="form-label">Название заметки</label>
          {{ form.name }}
        </div>
        <div class="mb-3">
          <label for="{{ form.description.id_for_label }}" class="form-label">Описание заметки</label>
          {{ form.description }}
        </div>
        <div class="mb-3">
          <label for="{{ form.actuality.id_for_label }}" class="form-check-label">Актуальность заметки</label>
          {{ form.actuality }}
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
      </form>
  </div>
{% endblock %}

posts/templates/posts/posts.html
{% extends 'posts/base.html' %}

{% block content %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for post in object_list %}
          <div class="col">
            <div class="card shadow-sm">
              <h2 class="card-text">{{ post.name }}</h2>
              <p class="card-text">{{ post.description }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% if post.actuality %}
                    <a class="btn btn-sm btn-success"
                       href="{% url 'posts:post_not_actuality' %}">
                       Выполнено
                    </a>
                  {% endif %}
                  <a class="btn btn-sm btn-warning"
                     href="{% url 'posts:post_update' post.id %}">
                     Изменить
                  </a>
<!--                  <button type="button" class="btn btn-sm btn-outline-secondary">Изменить</button>-->
                  <a class="btn btn-sm btn-danger"
                     href="{% url 'posts:post_delete' post.id %}">
                     Удалить
                  </a>
                </div>
                {% if post.actuality %}
                  <small class="text-muted">Не выполнено</small>
                {% else %}
                  <small class="text-muted">Выполнено</small>
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  {% if is_paginated %}
    <div class="container">
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
              <a class="page-link"
                 href="?page={{ page_obj.previous_page_number }}"
                 aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          {% endif %}
          {% for page in paginator.page_range %}
            {% if page_obj.number == page %}
              <li class="page-item disabled"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2  %}
              <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
              <a class="page-link"
                 href="?page={{ page_obj.next_page_number }}"
                 aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  {% endif %}
{% endblock %}